easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            list:
                fields: ['name']
            form:
                fields:
                    - {property: 'name'}
