easy_admin:
    entities:
        Forfait:
            class: App\Entity\Duration
            search:
                fields: ['name', 'description', 'days']
            list:
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'days', label: 'Nombre de jours', format: '%.0f'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: "Gestion de forfait"
                fields:
                    - {property: 'id', label: 'ID', type_options: { disabled: true }}
                    - {property: 'shortcode', label: 'Code court'}
                    - {property: 'name', label: 'Nom du forfait'}
                    - {property: 'days', label: 'Nombre de jours'}
                    - {property: 'description', label: 'Description'}
