easy_admin:
    entities:
        Forfait:
            class: App\Entity\Duration
            disabled_actions: ['delete']
            search:
                fields: ['name', 'description', 'days']
            list:
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'days', label: 'Nombre de jours', format: '%.0f'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'show', icon: 'eye', label: false, css_class: 'btn btn-secondary'}
            show: &durationFields
                title: "Gestion de forfait"
                fields:
                    - {property: 'id', label: 'ID', type_options: { disabled: true }}
                    - {property: 'shortcode', label: 'Code court', type_options: { disabled: true }}
                    - {property: 'name', label: 'Nom du forfait'}
                    - {property: 'days', label: 'Nombre de jours', format: '%.0f', type_options: { disabled: true }}
                    - {property: 'description', label: 'Description'}
            form: *durationFields