easy_admin:
    entities:
        Demande:
            class: App\Entity\ItemRequest
            disabled_actions: ['delete']
            search:
                fields: ['name', 'description']
            list:
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'createdAt', label: 'Créé le', format: 'd/m/Y'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'category', label: 'Catégorie(s)'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'enabled', label: 'Activé ?'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: "Gestion de demande"
                fields:
                    - {property: 'id', label: 'ID', type_options: { disabled: true }}
                    - {property: 'code', label: 'Code', type_options: { disabled: true }}
                    - {property: 'slug', label: 'Slug', type_options: { disabled: true }}
                    - {property: 'createdAt', label: 'Créé le', type_options: { disabled: true }}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'description', label: 'Description'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'enabled', label: 'Activé ?'}
        DemandeEnLigne:
            class: App\Entity\ItemRequest
            disabled_actions: ['new', 'delete']
            search:
                fields: ['name', 'description']
            list:
                dql_filter: 'entity.enabled = 1'
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'createdAt', label: 'Créé le', format: 'd/m/Y'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'category', label: 'Catégorie(s)'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'enabled', label: 'Activé ?'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: "Gestion de demande"
                fields:
                    - {property: 'id', label: 'ID', type_options: { disabled: true }}
                    - {property: 'code', label: 'Code', type_options: { disabled: true }}
                    - {property: 'slug', label: 'Slug', type_options: { disabled: true }}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'description', label: 'Description'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'enabled', label: 'Activé ?'}
        DemandeHorsLigne:
            class: App\Entity\ItemRequest
            disabled_actions: ['new', 'delete']
            search:
                fields: ['name', 'description']
            list:
                dql_filter: 'entity.enabled = 0'
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'createdAt', label: 'Créé le', format: 'd/m/Y'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'category', label: 'Catégorie(s)'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'enabled', label: 'Activé ?'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: "Gestion de demande"
                fields:
                    - {property: 'id', label: 'ID', type_options: { disabled: true }}
                    - {property: 'code', label: 'Code', type_options: { disabled: true }}
                    - {property: 'slug', label: 'Slug', type_options: { disabled: true }}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'description', label: 'Description'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'enabled', label: 'Activé ?'}