easy_admin:
    entities:
        PointDeRetraitJourHeure:
            class: App\Entity\PickupPointDayHour
            search:
                fields: ['pickupPoint.user.username', 'pickupPoint.user.email']
            list:
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'pickupPoint.user.username', label: 'Utilisateur'}
                    - {property: 'pickupPoint.user.email', label: 'Email'}
                    - {property: 'pickupPoint', label: 'Point de retrait'}
                    - {property: 'day', label: 'Jour', format: '%.0f', template: 'admin/_parts/week_days_format.html.twig'}
                    - {property: 'begin', label: 'Heure de début'}
                    - {property: 'end', label: 'Heure de fin'}
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: "Gestion des tranches horaires"
                fields:
                    - {property: 'id', label: 'ID', type_options: { disabled: true }}
                    - {property: 'pickupPoint', label: 'Point de retrait'}
                    - {property: 'day', label: 'Jour', type: 'choice', type_options: { choices: {'Lundi': '1', 'Mardi': '2', 'Mercredi': '3', 'Jeudi': '4', 'Vendredi': '5', 'Samedi': '6', 'Dimanche': '0'} } }
                    - {property: 'begin', label: 'Heure de début'}
                    - {property: 'end', label: 'Heure de fin'}