easy_admin:
    entities:
        Rubrique:
            class: App\Entity\Rubric
            disabled_actions: ['delete']
            list:
                fields:
                    - {property: 'name', label: 'Nom'}
                    - {property: 'slug', label: 'Slug'}
                    - {property: 'createdAt', label: 'Créé le', format: 'd/m/Y'}
                    - {property: 'category', label: 'Catégories'}
                    - {property: 'attributes', label: 'Attributs'}

                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: 'Modification de rubrique'
                fields:
                    - {property: 'name', label: 'Nom'}
                    - {property: 'description', label: 'Description'}
                    - {property: 'attributes', label: 'Attributs'}
