easy_admin:
    entities:
        TagSimple:
            class: App\Entity\Tag
            disabled_actions: ['new']
            search: &tagSimpleSearch
                fields: ['name']
            list:
                fields: &tagSimpleListFields
                    - {property: 'id', label: 'ID'}
                    - {property: 'slug', label: 'Slug'}
                    - {property: 'createdAt', label: 'Créé le', format: 'd/m/Y'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'item', label: 'Produit(s)'}
                actions: &tagSimpleActions
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form: &tagSimpleForm
                title: "Gestion de tag"
                fields:
                    - {property: 'id', label: 'ID', type_options: { disabled: true }}
                    - {property: 'createdAt', label: 'Créé le', type_options: { disabled: true }}
                    - {property: 'slug', label: 'Slug'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'description', label: 'Description'}
                    - {property: 'user', label: 'Créé par'}
                    - {property: 'item', label: 'Produit(s)'}
                    - {property: 'rubric', label: 'Rubrique'}
        Tag:
            class: App\Entity\Tag
            search: *tagSimpleSearch
            list:
                fields: &tagListFields
                    <<: *tagSimpleListFields
#                    <<: {property: 'rubric', label: 'Rubrique(s)'}
                actions: *tagSimpleActions
            form: *tagSimpleForm
        TagCat:
            class: App\Entity\Tag
            disabled_actions: ['new']
            search: *tagSimpleSearch
            list:
                fields: *tagListFields
                actions: *tagSimpleActions
            form: *tagSimpleForm