easy_admin:
    design:
        menu:
            - label: 'Comptes'
              icon: 'newspaper-o'
              children:
                  - {entity: 'Utilisateur',  label: 'Tous les comptes'}
                  - {entity: 'UtilisateurNonValide',  label: 'Comptes non validés'}
                  - {entity: 'UtilisateurValide',  label: 'Comptes validés'}
                  - {entity: 'UtilisateurFerme',  label: 'Comptes fermés'}
                  - {entity: 'UtilisateurSuspendu',  label: 'Comptes suspendus'}
                  - {entity: 'UtilisateurBanni',  label: 'Comptes bannis'}
            - label: 'Produits'
              icon: 'newspaper-o'
              children:
                  - {entity: 'ProduitHorsLigne',  label: 'Produits hors ligne'}
                  - {entity: 'ProduitEnLigne',  label: 'Produits en ligne'}
                  - {entity: 'ProduitDesactive',  label: 'Produits désactivés *'}
                  - {entity: 'Produit',  label: 'Tous les produits'}
            - label: 'Locations'
              icon: 'newspaper-o'
              children:
                  - {entity: 'LocationEnAttente',  label: 'Locations en attente'}
                  - {entity: 'LocationValidee',  label: 'Locations validées'}
                  - {entity: 'LocationTerminee',  label: 'Locations terminées'}
                  - {entity: 'LocationAnnuleeLoueur',  label: 'Annulées par le propriétaire'}
                  - {entity: 'LocationAnnuleeLocataire',  label: 'Annulées par le locataire'}
                  - {entity: 'LocationDesactivee',  label: 'Locations désactivées'}
                  - {entity: 'Location',  label: 'Toutes les locations'}
            - label: 'Evaluations'
              icon: 'newspaper-o'
              children:
                  - {entity: 'EvaluationEnAttente',  label: 'Evaluations en attente'}
                  - {entity: 'EvaluationLoueur',  label: 'Evaluations des loueurs'}
                  - {entity: 'EvaluationLocataire',  label: 'Evaluations des locataires'}
                  - {entity: 'Evaluation',  label: 'Evaluations désactivées *'}
                  - {entity: 'Evaluation',  label: 'Toutes les évaluations'}
            - label: 'Tags'
              icon: 'newspaper-o'
              children:
                  - {entity: 'Tag',  label: 'Tous les tags'}
                  - {entity: 'TagSimple',  label: 'Tags simples'}
                  - {entity: 'TagCat',  label: 'Tags liés aux rubriques'}
            - label: "Demandes d'objets"
              icon: 'newspaper-o'
              children:
                  - {entity: 'DemandeHorsLigne',  label: "Demandes hors ligne"}
                  - {entity: 'DemandeNonPourvue',  label: "Demandes non pourvues *"}
                  - {entity: 'DemandeEnLigne',  label: "Demandes en ligne"}
                  - {entity: 'Demande',  label: "Toutes les demandes"}
            - label: "Propositions d'objets"
              icon: 'newspaper-o'
              children:
                  - {entity: 'PropositionHorsLigne',  label: "Propositions hors ligne"}
                  - {entity: 'PropositionEnLigne',  label: "Propositions en ligne"}
                  - {entity: 'Proposition',  label: "Toutes les propositions"}
            - label: 'Points de retrait'
              icon: 'newspaper-o'
              children:
                  - {entity: 'PointDeRetrait',  label: 'Tous les points de retrait'}
                  - {entity: 'PointDeRetraitJourHeure',  label: 'Toutes les tranches horaires'}
            - label: 'Prix'
              icon: 'newspaper-o'
              children:
                  - {entity: 'Forfait',  label: 'Les types de forfaits'}
                  - {entity: 'Prix',  label: 'Tous les prix des produits'}
            - label: 'Structure'
              icon: 'newspaper-o'
              children:
                  - {entity: 'Zone',  label: 'Zones'}
                  - {entity: 'Rubrique',  label: 'Rubriques'}
                  - {entity: 'Categorie',  label: 'Catégories'}
                  - {entity: 'Attribut',  label: 'Attributs'}
                  - {entity: 'ValeurDAttribut',  label: "Valeurs d'attribut"}
            - label: 'Env: %env(APP_ENV)%'